-- Add audience-specific public ad placement types.
ALTER TABLE `AdPlacement`
  MODIFY `type` ENUM('LOGIN_PAGE_BANNER','PUBLIC_PARTNER_STRIP','RESOURCE_SPONSOR','PARENT_LOGIN_BANNER','RESULTS_CHECKER_SPONSOR','SIGNUP_PARTNER_STRIP') NOT NULL;
